server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/plazoleta-restaurantes
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 123456
  expiration: 1

security:
  role:
    propietario: PROPIETARIO
    admin: ADMINISTRADOR

appDescription: "Plazoleta Restaurantes"
appVersion: "1.0.0"
